Resources:
  CreateRequestFunctionServiceRoleC760CF9A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: HandleMyCaseLambdaFunctions/CreateRequestFunction/ServiceRole/Resource
  CreateRequestFunctionServiceRoleDefaultPolicy47CAC7D2:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::ImportValue: HandleMyCaseDynamoTables:ExportsOutputFnGetAtttable8235A42EArn0A2BE513
              - Fn::Join:
                  - ""
                  - - Fn::ImportValue: HandleMyCaseDynamoTables:ExportsOutputFnGetAtttable8235A42EArn0A2BE513
                    - /index/*
        Version: "2012-10-17"
      PolicyName: CreateRequestFunctionServiceRoleDefaultPolicy47CAC7D2
      Roles:
        - Ref: CreateRequestFunctionServiceRoleC760CF9A
    Metadata:
      aws:cdk:path: HandleMyCaseLambdaFunctions/CreateRequestFunction/ServiceRole/DefaultPolicy/Resource
  CreateRequestFunction6DB3417D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851S3BucketADD123B1
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851S3VersionKeyB12D4D36
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851S3VersionKeyB12D4D36
      Role:
        Fn::GetAtt:
          - CreateRequestFunctionServiceRoleC760CF9A
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      Runtime: nodejs14.x
    DependsOn:
      - CreateRequestFunctionServiceRoleDefaultPolicy47CAC7D2
      - CreateRequestFunctionServiceRoleC760CF9A
    Metadata:
      aws:cdk:path: HandleMyCaseLambdaFunctions/CreateRequestFunction/Resource
      aws:asset:path: asset.34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851
      aws:asset:property: Code
  CreateSignedUrlServiceRole03FD8FFB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: HandleMyCaseLambdaFunctions/CreateSignedUrl/ServiceRole/Resource
  CreateSignedUrl262E5973:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bbS3Bucket5230EEBF
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bbS3VersionKey7C92AED1
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bbS3VersionKey7C92AED1
      Role:
        Fn::GetAtt:
          - CreateSignedUrlServiceRole03FD8FFB
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      Runtime: nodejs14.x
    DependsOn:
      - CreateSignedUrlServiceRole03FD8FFB
    Metadata:
      aws:cdk:path: HandleMyCaseLambdaFunctions/CreateSignedUrl/Resource
      aws:asset:path: asset.c6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bb
      aws:asset:property: Code
  FunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      Cors:
        - "*"
      TargetFunctionArn:
        Fn::GetAtt:
          - CreateSignedUrl262E5973
          - Arn
    Metadata:
      aws:cdk:path: HandleMyCaseLambdaFunctions/FunctionUrl
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=2.15.0,@aws-cdk/assets=1.85.0,@aws-cdk/aws-apigateway=1.123.0,@aws-cdk/aws-applicationautoscaling=1.85.0,@aws-cdk/aws-autoscaling=1.85.0,@aws-cdk/aws-autoscaling-common=1.85.0,@aws-cdk/aws-autoscaling-hooktargets=1.85.0,@aws-cdk/aws-certificatemanager=1.101.0,@aws-cdk/aws-cloudformation=1.85.0,@aws-cdk/aws-cloudfront=1.101.0,@aws-cdk/aws-cloudfront-origins=1.101.0,@aws-cdk/aws-cloudwatch=1.85.0,@aws-cdk/aws-codeartifact=1.85.0,@aws-cdk/aws-codebuild=1.85.0,@aws-cdk/aws-codeguruprofiler=1.85.0,@aws-cdk/aws-codepipeline=1.85.0,@aws-cdk/aws-codepipeline-actions=1.85.0,@aws-cdk/aws-cognito=1.85.0,@aws-cdk/aws-dynamodb=1.119.0,@aws-cdk/aws-ec2=1.85.0,@aws-cdk/aws-ecr=1.85.0,@aws-cdk/aws-ecr-assets=1.85.0,@aws-cdk/aws-ecs=1.85.0,@aws-cdk/aws-elasticloadbalancingv2=1.101.0,@aws-cdk/aws-events=1.85.0,@aws-cdk/aws-events-targets=1.85.0,@aws-cdk/aws-iam=1.85.0,@aws-cdk/aws-kms=1.85.0,@aws-cdk/aws-lambda=1.85.0,@aws-cdk/aws-lambda-event-sources=1.123.0,@aws-cdk/aws-lambda-nodejs=1.123.0,@aws-cdk/aws-logs=1.85.0,@aws-cdk/aws-rds=1.129.0,@aws-cdk/aws-s3=1.119.0,@aws-cdk/aws-s3-assets=1.85.0,@aws-cdk/aws-s3-notifications=1.123.0,@aws-cdk/aws-sam=1.129.0,@aws-cdk/aws-secretsmanager=1.129.0,@aws-cdk/aws-servicediscovery=1.85.0,@aws-cdk/aws-sns=1.85.0,@aws-cdk/aws-sns-subscriptions=1.123.0,@aws-cdk/aws-sqs=1.85.0,@aws-cdk/aws-ssm=1.85.0,@aws-cdk/cloud-assembly-schema=1.85.0,@aws-cdk/core=1.119.0,@aws-cdk/custom-resources=1.85.0,@aws-cdk/cx-api=1.85.0,@aws-cdk/region-info=1.85.0,jsii-runtime=node.js/v14.18.0
    Metadata:
      aws:cdk:path: HandleMyCaseLambdaFunctions/CDKMetadata/Default
Parameters:
  AssetParameters34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851S3BucketADD123B1:
    Type: String
    Description: S3 bucket for asset "34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851"
  AssetParameters34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851S3VersionKeyB12D4D36:
    Type: String
    Description: S3 key for asset version "34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851"
  AssetParameters34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851ArtifactHashDC041BF7:
    Type: String
    Description: Artifact hash for asset "34c3702072cb671416ff6c4c3048f6fae2536aeda67ce12693285b02237b6851"
  AssetParametersc6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bbS3Bucket5230EEBF:
    Type: String
    Description: S3 bucket for asset "c6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bb"
  AssetParametersc6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bbS3VersionKey7C92AED1:
    Type: String
    Description: S3 key for asset version "c6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bb"
  AssetParametersc6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bbArtifactHash9BC9BE47:
    Type: String
    Description: Artifact hash for asset "c6a4714c6ebc0195a762e3515dc11e0ba7b4271b446b7c148e978af84f0049bb"

